### ISSUE TITLE
Peer Review by Divya Gupta #2 for https://github.com/Stary54264/relationship_between_attributes_and_whether_dih_exists_in_toronto_libraries

### ISSUE THREAD

**Issue by gdivyagupta** [Stary54264/relationship_between_facilities_and_area_of_toronto_libraries#1]
Summary
This repo aims to analyse the factors influencing the presence of Designated Innovation Hubs in Toronto libraries. The paper is incomplete, but the topic is appropriately chosen and the model has been developed. 

Strong positive points:
1. The paper is structured well and gives the reader a clear outline for how the author aims to add information later. Great job on adding the table of contents as well!
2. The topic chosen has robust datasets and can be explored clearly to satisfy the aims of this paper. The author makes it clear that they aim to develop a predictive model that can analyse the facilities of Toronto Libraries. 
3. The sketches created and included in the repo help understand the data.

Critical improvements needed:
1. It seems that the author has been developing their project by cleaning the dataset, conducting EDA, and developing their model. That's great! It is important to express these findings through some visualisations to assist the reader understand your aims and data.
2. More information is needed in your model and data section since the process is not completed yet. Make sure to include the estimand section when describing your data and model as well, not just the introduction. 
3. README file has not been updated yet. Please make sure you remove the rubric from it and ensure it fits the description of your project.

Suggestions for improvement:
1. Remove any useless files you don't need for your paper from your repo
2. Update ReadME file to give the reader an understanding of your project.
3. Include more writing to explain the process of developing your model. Currently, the reader has no understanding of your data or model but it seems like you are making great progress.

Evaluation:
R/Python cited (1/1 pts)
Cited. 
Data cited (1/1 pts)
Cited. 
Class paper (1/1 pts)
No indication that this is a class paper. 
LLM documentation (1/1 pts)
LLM usage  documented. 
Title (1.5/2 pts)
Informative title and subtitle. Consider including the full-form of DIH in your title since that is the first time the audience is coming across this acronym in your project. 
Author, date, and repo (2/2 pts)
Included. 
Abstract (0/4 pts)
Abstract included but not developed. 
Introduction (2.5/4 pts)
The introduction is well structured and clearly conveys the aims of the paper. It provides details about the type of models developed and the following structure of the paper. The introduction has a "Results" section which should be moved to the main Results section instead. It will benefit from further clarification on the need for this type of research/benefits of your model. 
Estimand (0.5/1 pts)
Not appropriately included. Casually mentioned in the Introduction but will benefit from a proper sub section. 
Data (2/10 pts)
Data section is included and well structured but not developed.
Measurement (0/4 pts)
Included but not developed. 
Model (2/10 pts)
Model section is included and well structured but not developed.
Results (0/10 pts)
Included but not developed. 
Discussion (0/10 pts)
Included and structured but not developed. No writing available so far. 
Prose (2/6 pts)
The paper is still unfinished and we only have the Introduction section to work with. The grammar and structure of the Introduction is well done. 
Cross-references (0/1 pts)
No graphs included. 
Captions (0/2 pts)
No graphs included. 
Graphs/tables/etc (0/4 pts)
No graphs included. 
Surveys, sampling, and observational data appendix (0/10 pts)
Not included. 
Referencing (4/4 pts)
Properly referenced. References.bib used. 
Commits (1.5/2 pts)
Some commits included. Will benefit from more commits. 
Sketches (1/2 pts)
Sketches included in the repo are useful in understanding the data. More sketches can be included. 
Simulation (4/4 pts)
Data is properly simulated and the scripts are appropriately labelled.
Tests (4/4 pts)
Has a lot of simulated and actual tests that cover a wide array of scenarios in the data. 
Parquet (1/1 pts)
Parquet file included.
Reproducible workflow (3/4 pts)
Github repo is reproducible, easy to follow, well organized, and has a lot of information. README not updated. 
Enhancements (0/4 pts)
No enhancements included. 
Miscellaneous (0/3 pts)
Unfinished work. 
Estimated overall mark:
[35] out of [112].
Any other comments:
Seems like you're making good progress with the code, sketches, writing and understanding your model. Best of luck!

**Comment by Stary54264** [comment]
Problems fixed
